import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.scss";
import localFont from "next/font/local";
import { CSSProperties } from "react";
import Header from "./layout/header/Header";
import Footer from "./layout/footer/Footer";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
});

const jqka = localFont({ src: "./fonts/jqka.ttf" });
export const metadata: Metadata = {
  title: "DeLux",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={jqka.className}
        style={
          {
            "--fontMain": jqka.style.fontFamily,
            "--fontAlt": fredoka.style.fontFamily,
          } as CSSProperties
        }
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
